"""Initial schema

Revision ID: e848002d1464
Revises: 
Create Date: 2025-11-25 01:47:51.060976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e848002d1464'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('client_ip', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_client_ip'), 'sessions', ['client_ip'], unique=False)
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('flows',
    sa.Column('flow_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('request_size', sa.Integer(), nullable=False),
    sa.Column('response_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('flow_id')
    )
    op.create_index(op.f('ix_flows_host'), 'flows', ['host'], unique=False)
    op.create_index(op.f('ix_flows_session_id'), 'flows', ['session_id'], unique=False)
    op.create_index(op.f('ix_flows_timestamp'), 'flows', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flows_timestamp'), table_name='flows')
    op.drop_index(op.f('ix_flows_session_id'), table_name='flows')
    op.drop_index(op.f('ix_flows_host'), table_name='flows')
    op.drop_table('flows')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_client_ip'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###

